BU KODDA ÖZETLE ŞUNLAR OLCAK;
#Pratik sutun seçme
#Loc metodu
#İloc metodu
#Çoklu seçme
#Çoklu filtreleme, süzme

In [2]:
import pandas as pd 
import numpy as np

In [6]:
film = pd.read_csv("DataSets/imdbratings.csv")
film.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

# seçme
Genel olarak 3 türlü seçme yapabiliriz;
1- köşeli parantez kullanmak.
2- loc methodunu kullanmak = 2 değer girilir ilk değer satırı, 2. değer sutunu gösterir. bu methodda etiket girilir
3- iloc methodunu kullanmak = yukardakiyle aynı fakat seçiceğimiz satır ve sutunların indexleri girilir.

In [9]:
film["title"].head() #title sutununun ilk 5 satırı

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                Pulp Fiction
Name: title, dtype: object

In [11]:
film[["title","genre","duration"]].head() #2 den çok ekrana yazdırmak istersek parantez içindwe parantez kullanılarak yapılır.

                      title   genre  duration
0  The Shawshank Redemption   Crime       142
1             The Godfather   Crime       175
2    The Godfather: Part II   Crime       200
3           The Dark Knight  Action       152
4              Pulp Fiction   Crime       154

# LOC METHODU
Loc methodu için satır ve sutun etiketlerini girmek gerekir. ilk değer satır 2. sutunu gösterir.

In [14]:
film.loc[[0,2,4],] #vırgulu koymayı unutma. loc methodunda ondan sonra bieş geliceğini anlamanda çok yardımcı olur.

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [15]:
film.loc[0:5,]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."

In [16]:
#Loc ile sutun işlemleri;
film.loc[0:5,"title"]

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                Pulp Fiction
5                12 Angry Men
Name: title, dtype: object

In [17]:
#sutunları dilimlemek istersek şöyle yaparız;
film.loc[0:5,"title":"genre"]

                      title content_rating   genre
0  The Shawshank Redemption              R   Crime
1             The Godfather              R   Crime
2    The Godfather: Part II              R   Crime
3           The Dark Knight          PG-13  Action
4              Pulp Fiction              R   Crime
5              12 Angry Men      NOT RATED   Drama

In [18]:
#loc methodunda sadece sutunları sıralayabliriz ;
film.loc[:,"title":"genre"]

                                               title content_rating      genre
0                           The Shawshank Redemption              R      Crime
1                                      The Godfather              R      Crime
2                             The Godfather: Part II              R      Crime
3                                    The Dark Knight          PG-13     Action
4                                       Pulp Fiction              R      Crime
..                                               ...            ...        ...
974                                          Tootsie             PG     Comedy
975                      Back to the Future Part III             PG  Adventure
976  Master and Commander: The Far Side of the World          PG-13     Action
977                                      Poltergeist             PG     Horror
978                                      Wall Street              R      Crime

[979 rows x 3 columns]

In [19]:
#LOC METHODU İLE SÜZME
film.loc[film.genre =="Crime",] #FİLM TURU CRİME OLAN SATIRLAR FİLTRELENDİ.

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
...,...,...,...,...,...,...
927,7.5,Brick,R,Crime,110,"[u'Joseph Gordon-Levitt', u'Lukas Haas', u'Emi..."
931,7.4,Mean Streets,R,Crime,112,"[u'Robert De Niro', u'Harvey Keitel', u'David ..."
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [20]:
film.loc[film.genre =="Crime","title"] #title sutunu crime değerine göre suzulmuş oldu. birden fazla değer allmak için köşeli parantez kullanıyoruz.

0      The Shawshank Redemption
1                 The Godfather
2        The Godfather: Part II
4                  Pulp Fiction
21                  City of God
                 ...
927                       Brick
931                Mean Streets
950                       Bound
969         Law Abiding Citizen
978                 Wall Street
Name: title, Length: 124, dtype: object

In [23]:
film.loc[film.genre =="Crime","title":"duration",] #dilimlenmiş hali

                        title content_rating  genre  duration
0    The Shawshank Redemption              R  Crime       142
1               The Godfather              R  Crime       175
2      The Godfather: Part II              R  Crime       200
4                Pulp Fiction              R  Crime       154
21                City of God              R  Crime       130
..                        ...            ...    ...       ...
927                     Brick              R  Crime       110
931              Mean Streets              R  Crime       112
950                     Bound              R  Crime       108
969       Law Abiding Citizen              R  Crime       109
978               Wall Street              R  Crime       126

[124 rows x 4 columns]

In [24]:
film.loc[film.genre =="Crime",["title","duration"]] #seçme bu şekilde.

                        title  duration
0    The Shawshank Redemption       142
1               The Godfather       175
2      The Godfather: Part II       200
4                Pulp Fiction       154
21                City of God       130
..                        ...       ...
927                     Brick       110
931              Mean Streets       112
950                     Bound       108
969       Law Abiding Citizen       109
978               Wall Street       126

[124 rows x 2 columns]

# İLOC METHODU;
İlocun, loc methodundan farkı etiket yerine satır ve sutunların indexlerini girmemiz gerekir. İlk değer satır, 2. değer sutundur.

In [26]:
film.iloc[:,0].head()

0    9.3
1    9.2
2    9.1
3    9.0
4    8.9
Name: star_rating, dtype: float64

In [27]:
film.columns #burdan indexleri bulabiliriz.

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [28]:
film.iloc[:,[0,3]] #0. ve 3. indexe sahip sutunlar yazılmış oldu.

     star_rating      genre
0            9.3      Crime
1            9.2      Crime
2            9.1      Crime
3            9.0     Action
4            8.9      Crime
..           ...        ...
974          7.4     Comedy
975          7.4  Adventure
976          7.4     Action
977          7.4     Horror
978          7.4      Crime

[979 rows x 2 columns]

In [29]:
film.iloc[:,0:3] #dilimleme yaparken parantez kalkıyo araya iki nokta geliyo

,star_rating,title,content_rating
0,9.3,The Shawshank Redemption,R
1,9.2,The Godfather,R
2,9.1,The Godfather: Part II,R
3,9.0,The Dark Knight,PG-13
4,8.9,Pulp Fiction,R
...,...,...,...
974,7.4,Tootsie,PG
975,7.4,Back to the Future Part III,PG
976,7.4,Master and Commander: The Far Side of the World,PG-13
977,7.4,Poltergeist,PG
978,7.4,Wall Street,R

In [30]:
film.iloc[0:5,0:3]#dilimleme

   star_rating                     title content_rating
0          9.3  The Shawshank Redemption              R
1          9.2             The Godfather              R
2          9.1    The Godfather: Part II              R
3          9.0           The Dark Knight          PG-13
4          8.9              Pulp Fiction              R

In [31]:
film.iloc[0:5,:,]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

# ÇOKLU FİLTRELEME SÜZME

In [33]:
(film.duration>=200)&(film.genre =="Crime") # bu koşul boolean değer dönderir. eğer

0      False
1      False
2       True
3      False
4      False
       ...
974    False
975    False
976    False
977    False
978    False
Length: 979, dtype: bool

In [35]:
film[(film.duration>=200)&(film.genre =="Crime")|(film.genre == "Action")] #böyle yaparsak da bu şekidle gösterir

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
...,...,...,...,...,...,...
918,7.5,Running Scared,R,Action,122,"[u'Paul Walker', u'Cameron Bright', u'Chazz Pa..."
954,7.4,X-Men,PG-13,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [36]:
film[film.genre.isin(["Crime","Drama","Action"])] #türü parantez içindeki değerler süzülerek veri setinde ortaya çıkar.

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."